FROM microsoft/dotnet:2.1-sdk as build
WORKDIR /src
COPY ./ ./authService
WORKDIR /src/authService
RUN dotnet restore -nowarn:msb3202,nu1503
RUN dotnet build -c Debug -o /app
COPY appsettings.Development.json /app
COPY appsettings.Docker.json /app
COPY appsettings.DockerDev.json /app
COPY appsettings.json /app
COPY hosting.Development.json /app
COPY hosting.Docker.json /app
COPY hosting.DockerDev.json /app
COPY hosting.json /app
WORKDIR /app
# ENTRYPOINT ["dotnet", "authService.dll"]
